import Head from "next/head";
import CheckOutPage from "../../../components/Store/PaymentCheckout/CheckOutPage";
import styles from "../../../styles/Home.module.css";

const CheckOut = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Store Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <CheckOutPage />
      </main>
    </div>
  );
};

export default CheckOut;
