import Head from "next/head";
import Header from "../../components/Layout/Header";
import ContactLanding from "../../components/Contact/ContactLanding/ContactLanding";
import Footer from "../../components/Layout/Footer";
import styles from "../../styles/Home.module.css";
import GetInTouch from "../../components/Contact/GetInTouch";
import FansConnect from "../../components/Contact/FansConnect";

const Contact = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Contact Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <ContactLanding />
        <GetInTouch />
        <FansConnect />
      </main>
      <Footer />
    </div>
  );
};

export default Contact;
