import React from 'react'
import Head from "next/head"
import Header from '../../components/Layout/Header'
import HealthAndWellness from '../../components/Expressions/HealthAndWellness'
import Inspiration from '../../components/Expressions/Inspiration'
import Arts from '../../components/Expressions/Arts'
import ExpressionsLanding from '../../components/Expressions/ExpressionsLanding'
import Entertainment from '../../components/Expressions/Entertainment'
import Footer from '../../components/Layout/Footer'
import styles from "../../styles/Home.module.css"

const Expressions = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaffy Brand</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
       <Header />
       <ExpressionsLanding />
       <HealthAndWellness />
       <Inspiration />
       <Arts />
       <Entertainment />
      </main>
      <Footer />
    </div>
  )
}

export default Expressions