import Head from "next/head";
import Header from "../../components/Layout/Header";
import Footer from "../../components/Layout/Footer";
import styles from "../../styles/Shop.module.css";
import MailingList from "../../components/Store/MailingList";
import CartPage from "../../components/Store/Cart/CartPage";

const Cart = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Cart Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <CartPage />
        <MailingList />
      </main>
      <Footer />
    </div>
  );
};

export default Cart;
