import Head from "next/head";
import Header from "../../components/Layout/Header";
import Footer from "../../components/Layout/Footer";
import styles from "../../styles/Shop.module.css";
import StoreLanding from "../../components/Store/StoreLanding";
import StoreCollections from "../../components/Store/StoreCollections/StoreCollections";
import Collection from "../../components/Store/StoreCollections/Collection";
import MailingList from "../../components/Store/MailingList";
import ViewProduct from "../../components/Store/Product/ViewProduct/ViewProduct";
import ProductReviews from "../../components/Store/ProductReview/ProductReviews";

const Store = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Store Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <StoreLanding />
        <StoreCollections />
        <Collection name={"T-Shirts"} isInStoreHome={true} />
        <Collection name={"T-Shirts"} isInStoreHome={false} />
        <Collection name={"For Dancers"} isInStoreHome={true} />
        <ViewProduct />
        <ProductReviews />
        <MailingList />
      </main>
      <Footer />
    </div>
  );
};

export default Store;
