import Head from 'next/head'
import Foundation from '../../components/Impact/Foundation'
import Header from '../../components/Layout/Header'
import Footer from '../../components/Layout/Footer'
import styles from "../../styles/Home.module.css"
import ImpactLanding from '../../components/Impact/ImpactLanding'
import SuccessStories from '../../components/Impact/SuccessStories'
import Synopsis from '../../components/Impact/Synopsis/Synopsis'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaffy Brand</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
       <Header />
       <ImpactLanding />
       <SuccessStories />
       <Synopsis />
       <Foundation />
       
      </main>
      <Footer />
    </div>
  )
}
