import Head from "next/head";
import Header from "../../../components/Layout/Header";
import StoreHeader from "../../../components/Store/StoreHeader/StoreHeader";
import Collection from "../../../components/Store/StoreCollections/Collection";
import MailingList from "../../../components/Store/MailingList";
import Footer from "../../../components/Layout/Footer";
import styles from "../../../styles/Shop.module.css";

// export const getStaticPaths = async () => {
//     const res await
// }

const CollectionPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>KAFFY Store {id} Collection</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <StoreHeader />
        <Collection name={`${id}`} isInStoreHome={false} />
        <MailingList />
      </main>
      <Footer />
    </div>
  );
};


export default CollectionPage;
