import Head from "next/head";
import Cookies from 'js-cookie'
import Services from "../components/Services/Services";
import SuccessStories from "../components/Impact/SuccessStories";
import GetInTouch from "../components/Contact/GetInTouch";
import Story from "../components/About/Story";
import Footer from "../components/Layout/Footer";
import Header from "../components/Layout/Header";
import Landing from "../components/Landing";
import VaultVideos from "../components/Vault/VaultVideos";
import BrandsWorkedWith from "../components/Expressions/BrandsWorkedWith";
import Featured from "../components/Expressions/Featured";
import styles from "../styles/Home.module.css";

import { db } from "../firebase";
import { collection, getDocs } from "firebase/firestore";



// const api = Cookies.withAttributes({ expires: 7, path: '', domain: '.youtube.com', sameSite: 'None', secure: true })

// const videosCollectionRef = collection(db, "videos")
// const videosEmbedIdCollectionRef = collection(db, "videosEmbedId")
const contactDetailsCollectionRef = collection(db, "contactDetails");
const successStoriesCollectionRef = collection(db, "successStories");
// cookie('cookie2', 'value2', { sameSite: 'None', secure: true });

// const YOUTUBE_PLAYLIST_ITEMS_API = "https://www.googleapis.com/youtube/v3/playlistItems"

export async function getStaticProps() {
  // const videosDataFrb = await getDocs(videosCollectionRef);
  // const videosEmbedIdData = await getDocs(videosEmbedIdCollectionRef)

  const contactDetailsData = await getDocs(contactDetailsCollectionRef);

  const successStoriesData = await getDocs(successStoriesCollectionRef);

  // const videosPlaylist = videosDataFrb.docs.map(doc =>  {
  //   return (
  //     {...doc.data(), id: doc.id}
  //   )
  // })[0]

  // const videosData = videosEmbedIdData.docs.map(doc =>  {
  //   return (
  //     {...doc.data(), id: doc.id}
  //   )
  // })

  // const res = await fetch(`${YOUTUBE_PLAYLIST_ITEMS_API}?part=snippet&playlistId=${videosPlaylist.playListCode}&maxResults=50&key=${process.env.YOUTUBE_API_KEY}`)
  // const videosData = await res.json();

  const videosData = [{ id: "Yq99FyfnGxA", type:"landscape", from: "youtube" }, { id: "41FLPJ5_Qwk", type: "portrait", from: "youtube" }];

  const contactDetails = contactDetailsData.docs.map((doc) => {
    return { ...doc.data(), id: doc.id };
  });

  const successStories = successStoriesData.docs.map((doc) => {
    return { ...doc.data(), id: doc.id };
  });

  return {
    props: {
      videosData,
      contactDetails,
      successStories,
    },
  };
}



export default function Home({videosData, successStories, contactDetails }) {
  // fetch("/api/hello")
  if (typeof window !== "undefined") {
    document.cookie = 'cookie4=value4; SameSite=None; Secure';
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaffy Brand</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Landing />

        <Featured
          img="/images/orange9.JPEG"
          name="CNN"
          title={"Nigerian choreographer is all about health"}
          description="Kaffy has brought up some of the best dancers in Nigeria and now she's giving back to her community through a healthcare partnership."
          featuredLink={
            "https://edition.cnn.com/videos/tv/2020/12/18/african-voices-choreographers-kaffy-tileh-pacbro-spc-intl.cnn"
          }
        />
        <SuccessStories successStories={successStories} />
        <Story />
        {/* {Cookies.set("video", "vdld", {sameSite: 'None', secure: true} )} */}
        {/* <VaultVideos videosData={videosData} /> */}
        <Services />
        <BrandsWorkedWith />
        <GetInTouch data={contactDetails} />
      </main>
      <Footer />
    </div>
  );
}
