import Head from 'next/head'
import Accolades from '../components/About/Accolades'
import MoreThanADancer from '../components/About/MoreThanADancer'
import Story from '../components/About/Story'
import Footer from '../components/Layout/Footer'
import Header from '../components/Layout/Header'
import Landing from '../components/Landing'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kaffy Brand</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
       <Header />
       <Landing />
       <Story />
       <MoreThanADancer />
       <Accolades />
       
      </main>
      <Footer />
    </div>
  )
}
