import Head from 'next/head'
import Header from '../../components/Layout/Header'
import Footer from '../../components/Layout/Footer'
import styles from "../../styles/Home.module.css"
import VaultLanding from '../../components/Vault/VaultLanding'
import VaultVideos from '../../components/Vault/VaultVideos'
import VaultPhotos from '../../components/Vault/VaultPhotos'

const YOUTUBE_PLAYLIST_ITEMS_API = "https://www.googleapis.com/youtube/v3/playlistItems"

export async function getServerSideProps() {
  const res = await fetch(`${YOUTUBE_PLAYLIST_ITEMS_API}?part=snippet&playlistId=PLEFMDQD6AJA0YKOE1v0IBCOU4lcqehIKc&maxResults=50&key=${process.env.YOUTUBE_API_KEY}`)
  const videosData = await res.json();
  return {
    props: {
      videosData
    }
  }
}

const Vault = ({ videosData}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Vault Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
       <Header />
       <VaultLanding />
       <VaultVideos videosData={videosData} />
       <VaultPhotos />
      </main>
      <Footer />
    </div>
  )
}

export default Vault
