import Head from 'next/head'
import Header from '../../components/Layout/Header'
import Footer from '../../components/Layout/Footer'
import styles from "../../styles/Home.module.css"
import VaultLanding from '../../components/Vault/VaultLanding'
import VaultVideos from '../../components/Vault/VaultVideos'
import VaultPhotos from '../../components/Vault/VaultPhotos'

import {db} from "../../firebase"
import { collection, getDocs } from 'firebase/firestore'

// const videosCollectionRef = collection(db, "videos")
const videosEmbedIdCollectionRef = collection(db, "videosEmbedId")
const photosCollectionRef = collection(db, "photos")

// const YOUTUBE_PLAYLIST_ITEMS_API = "https://www.googleapis.com/youtube/v3/playlistItems"

export async function getServerSideProps() {
  // const videosDataFrb = await getDocs(videosCollectionRef);
  const videosEmbedIdData = await getDocs(videosEmbedIdCollectionRef)
  const photosDataFrb = await getDocs(photosCollectionRef);


  // const videosPlaylist = videosDataFrb.docs.map(doc =>  {
  //   return (
  //     {...doc.data(), id: doc.id}
  //   )
  // })[0]

  const videosData = videosEmbedIdData.docs.map(doc =>  {
    return (
      {...doc.data(), id: doc.id}
    )
  })


  const photosData = photosDataFrb.docs.map(doc =>  {
    return (
      {...doc.data(), id: doc.id}
    )
  })

  // const res = await fetch(`${YOUTUBE_PLAYLIST_ITEMS_API}?part=snippet&playlistId=${videosPlaylist.playListCode}&maxResults=50&key=${process.env.YOUTUBE_API_KEY}`)
  // const videosData = await res.json();
  return {
    props: {
      videosData,
      photosData: photosData,
    }
  }
}

const Vault = ({ videosData, photosData }) => {
 
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Vault Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
       <Header />
       <VaultLanding />
       <VaultVideos videosData={videosData} />
       <VaultPhotos photosData={photosData} />
      </main>
      <Footer />
    </div>
  )
}

export default Vault
