import Head from 'next/head'
import Header from '../../components/Layout/Header'
import Footer from '../../components/Layout/Footer'
import styles from "../../styles/Home.module.css"
import VaultLanding from '../../components/Vault/VaultLanding'
import VaultVideos from '../../components/Vault/VaultVideos'
import VaultPhotos from '../../components/Vault/VaultPhotos'

const Vault = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>IAMKAFFY Brand Vault Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
       <Header />
       <VaultLanding />
       <VaultVideos />
       <VaultPhotos />
      </main>
      <Footer />
    </div>
  )
}

export default Vault
